carbon-design-system/carbon-addons-data-viz-react

.storybook/_container.scss, components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js, index.js, package.json, yarn.lock
Adds initial Line Graph component.
=> Line Graph

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Will close https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/21
=> fix(line-graph): add ability to scale in UTC format

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/28
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/26
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/25
=> Line graph update fix

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/32
=> fix(linegraph): bump minimum empty threshold to 2 data points

components/PieChart/PieChart.js, components/PieChart/PieChart.story.js
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/27
=> fix(pie-chart): ensure pie-chart updates on new props

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Adds in initial support for multi line graphs. Expected format: `[num, num..., date]`
=> Multi line graph

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Just adding some more checks so console errors aren't thrown. Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/40
=> fix(line-graph): add more null checks

components/LineGraph/LineGraph.js
Make sure `totalLines` is recalculated on new data
=> fix(line-graph): make sure total lines are recalculated on new data

components/LineGraph/LineGraph.js
Moved data checks inside `onMouseMove` and `onMouseOut` functions
=> fix(line-graph): move data check inside mousemove

components/LineGraph/LineGraph.js
=> Fix rerender

README.md, components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
Adds `drawLine` prop to `LineGraph` to toggle drawing the line animation.  Also updated the `LineGraph` props on README.md and added a new story in the storybook for 'Updating without drawing line'.
=> feat(line-graph): add drawLine toggle prop

components/GaugeGraph/GaugeGraph.js, components/GaugeGraph/GaugeGraph.story.js, package.json, yarn.lock
Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/51
=> feat(gauge-graph): add ability to define custom ranges for gauge graph

components/LineGraph/LineGraph.js
Line graph will now resize by rerendering when a new height or width property is passed in
=> Linegraph resize

components/GaugeGraph/GaugeGraph.js, components/GaugeGraph/GaugeGraph.story.js, components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js, components/PieChart/PieChart.js, components/PieChart/PieChart.story.js, components/ScatterPlot/ScatterPlot.js
=> chore(lint): fix lint errors

components/BarGraph/BarGraph.js, components/BarGraph/BarGraph.story.js, components/GaugeGraph/GaugeGraph.js
Updates examples to use all 5 colors
=> fix(bar-graph): update examples

index.js, package.json
Adds `BarGraph` to the `exports` list
=> chore(export): add BarGraph to exports

package.json, yarn.lock
Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/72
=> chore(update): update dependencies

index.js, package.json, yarn.lock
Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/74
=> fix(index): export DataTooltip

components/DataTooltip/DataTooltip.js, components/DataTooltip/DataTooltip.story.js, components/DataTooltip/_data-tooltip.scss
Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/77
=> fix(data-tooltip): make sure text will overflow properly

README.md, scripts/build.js
Should correctly output sass files
=> fix(build): ensure sass files are output correctly

components/DataTooltip/DataTooltip.js, components/DataTooltip/DataTooltip.story.js, components/DataTooltip/_data-tooltip.scss
Closes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/83
- Story for all varieties
- `_data-tooltip.scss` - added styles for 4 - 6 items.
- `DataTooltip.js` - add class based on data length
=> Tooltip fix

components/DataTooltip/DataTooltip.js, components/DataTooltip/DataTooltip.story.js, components/DataTooltip/_data-tooltip.scss
=> fix(data-tooltip): update styles for single data with heading

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js
if showLegend prop is set to true (and seriesLabels.length > 0), render legend to right of line graph
=> feat(line-graph): add optional legend

components/LineGraph/LineGraph.js, yarn.lock
Ensures no duplicate id's. 
Fixes https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/95
=> fix(line-graph): ensure tooltip has unique id

components/LineGraph/LineGraph.js
Fixes #114 
Removes and redraws the legend if the component updates and the seriesLabels are different lengths
=> feat(linegraph): Add dynamic render for legend

README.md
=> Correcting path for SCSS import

components/PieChart/PieChart.js
Self explanatory - Full context in parent issue, Closes #122
=> Remove unnecessary cWRP from PieChart

package.json
Update `package.json` to trigger release
=> fix(package.json): prettier

components/LineGraph/LineGraph.js, components/LineGraph/LineGraph.story.js, package.json
we need to customize the Yxis tick size and format
=> feat: customize the yxis tick size and format
